Repository mo00ai/nakyum-market, pull requests merged in 2025-05, with the labels that each got.

#3 [Feature] Product, ActionBid , Dips, Image Entity 개발
  src/main/java/com/example/auction/AuctionApplication.java
  src/main/java/com/example/auction/common/entity/BaseEntity.java
  src/main/java/com/example/auction/domain/auctionbid/entity/AuctionBid.java
  src/main/java/com/example/auction/domain/dips/entity/Dips.java
  src/main/java/com/example/auction/domain/image/entity/Image.java
  src/main/java/com/example/auction/domain/product/entity/Product.java
  src/main/java/com/example/auction/domain/user/entity/User.java
Labels: Feature

#5 Feature/entity user
  src/main/java/com/example/auction/domain/user/entity/Role.java
  src/main/java/com/example/auction/domain/user/entity/User.java
Labels: Feature

#10 [Feature] 주문 생성 API 개발
  src/main/java/com/example/auction/common/entity/BaseCreateTimeEntity.java
  src/main/java/com/example/auction/domain/order/controller/OrderController.java
  src/main/java/com/example/auction/domain/order/dto/request/OrderRequestDto.java
  src/main/java/com/example/auction/domain/order/dto/response/OrderResponseDto.java
  src/main/java/com/example/auction/domain/order/entity/Order.java
  src/main/java/com/example/auction/domain/order/entity/OrderItem.java
  src/main/java/com/example/auction/domain/order/exception/OrderErrorCode.java
  src/main/java/com/example/auction/domain/order/repository/OrderItemRepository.java
  src/main/java/com/example/auction/domain/order/repository/OrderRepository.java
  src/main/java/com/example/auction/domain/order/service/OrderService.java
  src/main/java/com/example/auction/domain/product/exception/ProductErrorCode.java
  src/main/java/com/example/auction/domain/product/repository/ProductRepository.java
Labels: Feature, Refactoring

#13 Feature/product
  build.gradle
  naver-checkstyle-rules.xml
  naver-checkstyle-suppressions.xml
  src/main/java/com/example/auction/common/annotation/ImageValid.java
  src/main/java/com/example/auction/common/constant/BusinessRuleConstants.java
  src/main/java/com/example/auction/common/exception/ErrorCode.java
  src/main/java/com/example/auction/config/ImageAspect.java
  src/main/java/com/example/auction/config/QueryDslConfig.java
  src/main/java/com/example/auction/config/RedisConfig.java
  src/main/java/com/example/auction/domain/image/entity/Image.java
  src/main/java/com/example/auction/domain/image/exception/ImageErrorCode.java
  src/main/java/com/example/auction/domain/image/repository/ImageRepository.java
  src/main/java/com/example/auction/domain/image/service/ImageService.java
  src/main/java/com/example/auction/domain/order/entity/OrderItem.java
  src/main/java/com/example/auction/domain/product/controller/ProductController.java
  src/main/java/com/example/auction/domain/product/dto/request/ProductRequestDto.java
  src/main/java/com/example/auction/domain/product/dto/request/ProductUpdateRequestDto.java
  src/main/java/com/example/auction/domain/product/dto/response/PageResponseDto.java
  src/main/java/com/example/auction/domain/product/dto/response/ProductResponseDto.java
  src/main/java/com/example/auction/domain/product/dto/response/ProductSaveResponseDto.java
  src/main/java/com/example/auction/domain/product/dto/response/ProductWithdrawResponseDto.java
  src/main/java/com/example/auction/domain/product/entity/Product.java
  src/main/java/com/example/auction/domain/product/repository/ProductRepository.java
  src/main/java/com/example/auction/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/auction/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/auction/domain/product/service/ProductService.java
  src/main/resources/application.properties
Labels: Feature

#17 Feature/dips
  src/main/java/com/example/auction/common/exception/ErrorCode.java
  src/main/java/com/example/auction/common/listener/RedisKeyExpirationListener.java
  src/main/java/com/example/auction/common/service/RedisService.java
  src/main/java/com/example/auction/config/RedisConfig.java
  src/main/java/com/example/auction/domain/dips/controller/DipsController.java
  src/main/java/com/example/auction/domain/dips/dto/response/DipsFindResponseDto.java
  src/main/java/com/example/auction/domain/dips/dto/response/DipsSaveResponseDto.java
  src/main/java/com/example/auction/domain/dips/exception/DipsErrorCode.java
  src/main/java/com/example/auction/domain/dips/repository/DipsRepository.java
  src/main/java/com/example/auction/domain/dips/service/DipsService.java
  src/main/java/com/example/auction/filter/JwtAuthenticationFilter.java
Labels: Feature

#31 [Feature] 내 낙찰된 아이템 주문하기 API 개발 및 자동 주문 기능 적용
  src/main/java/com/example/auction/domain/order/controller/OrderController.java
  src/main/java/com/example/auction/domain/order/dto/request/OrderRequestDto.java
  src/main/java/com/example/auction/domain/order/dto/response/OrderResponseDto.java
  src/main/java/com/example/auction/domain/order/entity/Order.java
  src/main/java/com/example/auction/domain/order/handler/AutoOrderEventHandler.java
  src/main/java/com/example/auction/domain/order/repository/OrderItemRepository.java
  src/main/java/com/example/auction/domain/order/service/OrderService.java
  src/main/java/com/example/auction/domain/product/repository/ProductRepository.java
  src/main/java/com/example/auction/domain/product/service/ProductService.java
  src/main/java/com/example/auction/domain/wonitem/exception/WonItemErrorCode.java
  src/main/java/com/example/auction/domain/wonitem/handler/WonItemKeyEventHandler.java
  src/main/java/com/example/auction/domain/wonitem/service/WonItemService.java
Labels: Feature, Test

#32 Feat/auctionbid create api with redis test #30
  naver-checkstyle-rules.xml
  src/main/java/com/example/auction/common/exception/ErrorCode.java
  src/main/java/com/example/auction/common/listener/RedisKeyExpirationListener.java
  src/main/java/com/example/auction/common/service/RedisService.java
  src/main/java/com/example/auction/config/RedisConfig.java
  src/main/java/com/example/auction/domain/auctionbid/controller/AuctionBidController.java
  src/main/java/com/example/auction/domain/auctionbid/dto/BidRedisDto.java
  src/main/java/com/example/auction/domain/auctionbid/dto/request/BidRequestDto.java
  src/main/java/com/example/auction/domain/auctionbid/repository/AuctionBidRepository.java
  src/main/java/com/example/auction/domain/auctionbid/service/AuctionBidRedisService.java
  src/main/java/com/example/auction/domain/auctionbid/service/AuctionBidService.java
  src/test/java/com/example/auction/domain/auctionbid/service/AuctionBidRedisServiceTest.java
Labels: Feature

#38 Feature/auctionbid save
  build.gradle
  src/main/java/com/example/auction/common/exception/ErrorCode.java
  src/main/java/com/example/auction/common/listener/RedisKeyExpirationListener.java
  src/main/java/com/example/auction/common/scheduler/ProductCountScheduler.java
  src/main/java/com/example/auction/common/service/RedisService.java
  src/main/java/com/example/auction/domain/auctionbid/dto/BidRedisDto.java
  src/main/java/com/example/auction/domain/auctionbid/entity/AuctionBid.java
  src/main/java/com/example/auction/domain/auctionbid/exception/AuctionBidErrorCode.java
  src/main/java/com/example/auction/domain/auctionbid/handler/AuctionBidKeyEventHandler.java
  src/main/java/com/example/auction/domain/auctionbid/repository/AuctionBidRepository.java
  src/main/java/com/example/auction/domain/auctionbid/service/AuctionBidRedisService.java
  src/main/java/com/example/auction/domain/auctionbid/service/AuctionBidService.java
  src/main/java/com/example/auction/domain/dips/service/DipsService.java
  src/main/java/com/example/auction/domain/product/controller/ProductController.java
  src/main/java/com/example/auction/domain/product/dto/request/ProductRequestDto.java
  src/main/java/com/example/auction/domain/product/dto/response/ProductResponseDto.java
  src/main/java/com/example/auction/domain/product/entity/Product.java
  src/main/java/com/example/auction/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/auction/domain/product/service/ProductService.java
  src/main/java/com/example/auction/domain/test/TestRequestDto.java
  src/main/java/com/example/auction/domain/test/controller/TestBidController.java
  src/main/java/com/example/auction/domain/test/dto
  src/main/java/com/example/auction/domain/test/repository/AuctionBidJdbcRepository.java
  src/main/java/com/example/auction/domain/test/repository/TestAuctionBidRepository.java
  src/main/java/com/example/auction/domain/user/auth/service/AuthService.java
  src/main/java/com/example/auction/domain/user/auth/service/EmailService.java
  src/main/java/com/example/auction/domain/wonitem/service/WonItemService.java
  src/main/java/com/example/auction/filter/JwtAuthenticationFilter.java
  src/main/resources/application-test.properties
  src/test/java/com/example/auction/auctionbid/AuctionBidTest.java
  src/test/java/com/example/auction/domain/auctionbid/service/AuctionBidRedisServiceTest.java
  src/test/java/com/example/auction/product/productScheduleTest.java
Labels: Feature

#45 Refactor/dips
  src/main/java/com/example/auction/common/service/RedisService.java
  src/main/java/com/example/auction/config/RedisConfig.java
  src/main/java/com/example/auction/domain/dips/controller/DipsController.java
  src/main/java/com/example/auction/domain/dips/service/DipsService.java
  src/main/java/com/example/auction/domain/product/service/ProductService.java
  src/main/java/com/example/auction/domain/user/auth/controller/AuthController.java
  src/main/java/com/example/auction/domain/user/auth/handler/CustomLogoutSuccessHandler.java
  src/test/java/com/example/auction/domain/product/service/ProductTest.java
Labels: Refactoring

#48 Refactor/dips
  src/main/java/com/example/auction/common/service/RedisService.java
  src/main/java/com/example/auction/domain/dips/repository/DipsRepository.java
  src/main/java/com/example/auction/domain/dips/service/DipsService.java
Labels: Refactoring
